# Generated by Django 5.0.1 on 2024-05-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="main_image",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="other_image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
